### ISSUE TITLE
'Collection was modified' exception thrown

### ISSUE THREAD

**Issue by iekdosha** [DevExpress-Examples/how-to-preserve-the-xtragrid-view-state-e776#1]
Hi, i get the following exception when trying to load a GridView state:
` "Collection was modified; enumeration operation may not execute."`
This is the relevant call stack:
   
```
at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()   
at . . .  .RefreshHelper.LoadExpansionViewInfo(ArrayList list) 
at . . .  .RefreshHelper.LoadViewInfo() 
   . . .
```
I did not share any inner list and did not modify any code.
Thank you :-)

**Comment by iekdosha** [comment]
I have discovered that the call : 
```cs
public void LoadExpansionViewInfo(ArrayList list)
        {
            if (view.GroupedColumns.Count == 0) return;
            view.BeginUpdate();
            try
            {
                view.CollapseAllGroups();
                foreach (RowInfo info in list)
                    ExpandRowByRowInfo(info);  \\ This call modifies the list
                }
            }
            finally
            {
                view.EndUpdate();
            }
        }

```
Will modify the list after reaching a call for the DevExpress method: SetRowExpanded which is called eventually from that method.

**Comment by LexEPoX** [comment]
Hello,
 
Please accept my apologies for such a late response. I tried to reproduce this behavior by grouping rows and restoring the grid's state but to no avail. Would you please provide me with the exact steps that led to the issue? Also, please clarify what version of our controls you used. I look forward to hearing back from you.

**Comment by LexEPoX** [comment]
I haven't heard back from you for some time, @iekdosha. I will close this issue for now. Feel free to re-open it if you need any further assistance.
